<?php
/**
 * Landings: cabecera (slider imágenes / YouTube + logo de proyecto) por fase editorial.
 * Campos en pestañas ACF: Prelanding y Landing completa.
 *
 * @package skema
 */

defined( 'ABSPATH' ) || exit;

/**
 * Registra grupo ACF en CPT landings.
 */
function theme_skema_acf_register_landing_hero_slider() {
	if ( ! function_exists( 'acf_add_local_field_group' ) ) {
		return;
	}

	acf_add_local_field_group(
		array(
			'key'                   => 'group_skema_landing_hero_slider',
			'title'                 => __( 'Cabecera (slider, copy prelanding y lead)', 'theme_skema' ),
			'fields'                => array(
				array(
					'key'   => 'field_skema_landing_hero_tab_pre',
					'label' => __( 'Prelanding', 'theme_skema' ),
					'name'  => '',
					'type'  => 'tab',
					'placement' => 'top',
				),
				array(
					'key'           => 'field_skema_lpre_hero_tipo',
					'label'         => __( 'Tipo de cabecera', 'theme_skema' ),
					'name'          => 'skema_lpre_hero_tipo',
					'type'          => 'select',
					'instructions'  => __( 'Misma lógica que el inicio: slider Slick con imágenes (escritorio + móvil opcional) o vídeos YouTube.', 'theme_skema' ),
					'choices'       => array(
						'none'    => __( 'Ninguna (solo contenido inferior)', 'theme_skema' ),
						'images'  => __( 'Slider de imágenes', 'theme_skema' ),
						'youtube' => __( 'Slider YouTube', 'theme_skema' ),
					),
					'default_value' => 'none',
					'allow_null'    => 0,
					'ui'            => 1,
					'return_format' => 'value',
				),
				array(
					'key'               => 'field_skema_lpre_slider_img',
					'label'             => __( 'Slides escritorio', 'theme_skema' ),
					'name'              => 'skema_lpre_slider_img',
					'type'              => 'repeater',
					'instructions'      => __( 'Imágenes a ancho completo (≥576px).', 'theme_skema' ),
					'min'               => 0,
					'max'               => 0,
					'layout'            => 'row',
					'button_label'      => __( 'Añadir slide', 'theme_skema' ),
					'sub_fields'        => array(
						array(
							'key'           => 'field_skema_lpre_slider_img_cell',
							'label'         => __( 'Imagen', 'theme_skema' ),
							'name'          => 'img',
							'type'          => 'image',
							'return_format' => 'array',
							'preview_size'  => 'medium',
							'required'      => 1,
						),
					),
					'conditional_logic' => array(
						array(
							array(
								'field'    => 'field_skema_lpre_hero_tipo',
								'operator' => '==',
								'value'    => 'images',
							),
						),
					),
				),
				array(
					'key'               => 'field_skema_lpre_slider_img_movil',
					'label'             => __( 'Slides móvil', 'theme_skema' ),
					'name'              => 'skema_lpre_slider_img_movil',
					'type'              => 'repeater',
					'instructions'      => __( 'Opcional: si queda vacío, en móvil se usan las mismas imágenes que en escritorio.', 'theme_skema' ),
					'layout'            => 'row',
					'button_label'      => __( 'Añadir slide móvil', 'theme_skema' ),
					'sub_fields'        => array(
						array(
							'key'           => 'field_skema_lpre_slider_img_movil_cell',
							'label'         => __( 'Imagen', 'theme_skema' ),
							'name'          => 'img',
							'type'          => 'image',
							'return_format' => 'array',
							'preview_size'  => 'medium',
							'required'      => 1,
						),
					),
					'conditional_logic' => array(
						array(
							array(
								'field'    => 'field_skema_lpre_hero_tipo',
								'operator' => '==',
								'value'    => 'images',
							),
						),
					),
				),
				array(
					'key'               => 'field_skema_lpre_slider_youtube',
					'label'             => __( 'Vídeos YouTube', 'theme_skema' ),
					'name'              => 'skema_lpre_slider_youtube',
					'type'              => 'repeater',
					'layout'            => 'row',
					'button_label'      => __( 'Añadir vídeo', 'theme_skema' ),
					'sub_fields'        => array(
						array(
							'key'   => 'field_skema_lpre_slider_youtube_url',
							'label' => __( 'URL del vídeo', 'theme_skema' ),
							'name'  => 'youtube_url',
							'type'  => 'url',
						),
					),
					'conditional_logic' => array(
						array(
							array(
								'field'    => 'field_skema_lpre_hero_tipo',
								'operator' => '==',
								'value'    => 'youtube',
							),
						),
					),
				),
				array(
					'key'           => 'field_skema_lpre_project_logo',
					'label'         => __( 'Logo del proyecto', 'theme_skema' ),
					'name'          => 'skema_lpre_project_logo',
					'type'          => 'image',
					'instructions'  => __( 'Opcional. En Prelanding se muestra dentro del hero junto al título.', 'theme_skema' ),
					'return_format' => 'array',
					'preview_size'  => 'medium',
				),
				array(
					'key'          => 'field_skema_lpre_hero_tagline',
					'label'        => __( 'Línea superior (etiqueta)', 'theme_skema' ),
					'name'         => 'skema_lpre_hero_tagline',
					'type'         => 'text',
					'instructions' => __( 'Ej.: Prelanzamiento 2026 · Proyecto VIS', 'theme_skema' ),
				),
				array(
					'key'          => 'field_skema_lpre_hero_heading',
					'label'        => __( 'Título principal (H1)', 'theme_skema' ),
					'name'         => 'skema_lpre_hero_heading',
					'type'         => 'text',
					'instructions' => __( 'Si queda vacío, se usa el título de la entrada.', 'theme_skema' ),
				),
				array(
					'key'   => 'field_skema_lpre_hero_subtitle',
					'label' => __( 'Subtítulo', 'theme_skema' ),
					'name'  => 'skema_lpre_hero_subtitle',
					'type'  => 'text',
				),
				array(
					'key'          => 'field_skema_lpre_hero_location',
					'label'        => __( 'Ubicación (línea corta)', 'theme_skema' ),
					'name'         => 'skema_lpre_hero_location',
					'type'         => 'text',
					'instructions' => __( 'Ej.: Valle del Cauca · Pacífico', 'theme_skema' ),
				),
				array(
					'key'          => 'field_skema_lpre_hero_intro',
					'label'        => __( 'Texto introductorio (prelanding y landing completa)', 'theme_skema' ),
					'name'         => 'skema_lpre_hero_intro',
					'type'         => 'wysiwyg',
					'instructions' => __( 'Mismo contenido en ambas fases: en prelanding va debajo del título en el hero; en landing completa, debajo de la ficha resumen y antes del contenido del editor.', 'theme_skema' ),
					'tabs'         => 'visual',
					'toolbar'      => 'basic',
					'media_upload' => 0,
					'delay'        => 0,
				),
				array(
					'key'          => 'field_skema_lpre_hero_points',
					'label'        => __( 'Viñetas destacadas', 'theme_skema' ),
					'name'         => 'skema_lpre_hero_points',
					'type'         => 'repeater',
					'layout'       => 'row',
					'button_label' => __( 'Añadir viñeta', 'theme_skema' ),
					'sub_fields'   => array(
						array(
							'key'   => 'field_skema_lpre_hero_points_text',
							'label' => __( 'Texto', 'theme_skema' ),
							'name'  => 'point_text',
							'type'  => 'text',
						),
					),
				),
				array(
					'key'          => 'field_skema_lpre_lead_title',
					'label'        => __( 'Título del bloque de contacto', 'theme_skema' ),
					'name'         => 'skema_lpre_lead_title',
					'type'         => 'text',
					'instructions' => __( 'Si queda vacío y hay formulario, se usa «Solicita información».', 'theme_skema' ),
				),
				array(
					'key'   => 'field_skema_lpre_lead_text',
					'label' => __( 'Texto bajo el título del bloque', 'theme_skema' ),
					'name'  => 'skema_lpre_lead_text',
					'type'  => 'textarea',
					'rows'  => 3,
				),
				array(
					'key'          => 'field_skema_lpre_lead_cf7',
					'label'        => __( 'Shortcode Contact Form 7', 'theme_skema' ),
					'name'         => 'skema_lpre_lead_cf7',
					'type'         => 'textarea',
					'rows'         => 2,
					'instructions' => __( 'Pega el shortcode del formulario (Contacto → formularios → copiar shortcode). Solo se aceptan shortcodes que empiecen por [contact-form-7 …].', 'theme_skema' ),
				),
				array(
					'key'          => 'field_skema_lpre_lead_anchor_id',
					'label'        => __( 'ID HTML del bloque (ancla)', 'theme_skema' ),
					'name'         => 'skema_lpre_lead_anchor_id',
					'type'         => 'text',
					'instructions' => __( 'Opcional. Por defecto: solicitar-informacion. Solo letras, números y guiones.', 'theme_skema' ),
					'default_value' => 'solicitar-informacion',
				),
				array(
					'key'   => 'field_skema_landing_hero_tab_land',
					'label' => __( 'Landing completa', 'theme_skema' ),
					'name'  => '',
					'type'  => 'tab',
					'placement' => 'top',
				),
				array(
					'key'           => 'field_skema_lland_hero_tipo',
					'label'         => __( 'Tipo de cabecera', 'theme_skema' ),
					'name'          => 'skema_lland_hero_tipo',
					'type'          => 'select',
					'instructions'  => __( 'Configuración independiente de la pestaña Prelanding. Se usa cuando la fase de la entrada es «Landing completa».', 'theme_skema' ),
					'choices'       => array(
						'none'    => __( 'Ninguna (solo contenido inferior)', 'theme_skema' ),
						'images'  => __( 'Slider de imágenes', 'theme_skema' ),
						'youtube' => __( 'Slider YouTube', 'theme_skema' ),
					),
					'default_value' => 'none',
					'allow_null'    => 0,
					'ui'            => 1,
					'return_format' => 'value',
				),
				array(
					'key'               => 'field_skema_lland_slider_img',
					'label'             => __( 'Slides escritorio', 'theme_skema' ),
					'name'              => 'skema_lland_slider_img',
					'type'              => 'repeater',
					'layout'            => 'row',
					'button_label'      => __( 'Añadir slide', 'theme_skema' ),
					'sub_fields'        => array(
						array(
							'key'           => 'field_skema_lland_slider_img_cell',
							'label'         => __( 'Imagen', 'theme_skema' ),
							'name'          => 'img',
							'type'          => 'image',
							'return_format' => 'array',
							'preview_size'  => 'medium',
							'required'      => 1,
						),
						array(
							'key'           => 'field_skema_lland_slider_img_slide_tagline',
							'label'         => __( 'Línea superior (solo este slide)', 'theme_skema' ),
							'name'          => 'slide_tagline',
							'type'          => 'text',
							'instructions'  => __( 'Opcional. Si se rellena, sustituye la etiqueta global del hero en esta diapositiva.', 'theme_skema' ),
						),
						array(
							'key'           => 'field_skema_lland_slider_img_slide_heading',
							'label'         => __( 'Título (solo este slide)', 'theme_skema' ),
							'name'          => 'slide_heading',
							'type'          => 'text',
							'instructions'  => __( 'Opcional. Si se rellena, sustituye el título global en esta diapositiva.', 'theme_skema' ),
						),
						array(
							'key'           => 'field_skema_lland_slider_img_slide_location',
							'label'         => __( 'Ubicación (solo este slide)', 'theme_skema' ),
							'name'          => 'slide_location',
							'type'          => 'text',
							'instructions'  => __( 'Opcional. Si se rellena, sustituye la ubicación global en esta diapositiva.', 'theme_skema' ),
						),
					),
					'conditional_logic' => array(
						array(
							array(
								'field'    => 'field_skema_lland_hero_tipo',
								'operator' => '==',
								'value'    => 'images',
							),
						),
					),
				),
				array(
					'key'               => 'field_skema_lland_slider_img_movil',
					'label'             => __( 'Slides móvil', 'theme_skema' ),
					'name'              => 'skema_lland_slider_img_movil',
					'type'              => 'repeater',
					'instructions'      => __( 'Opcional: si queda vacío, en móvil se usan las mismas imágenes que en escritorio.', 'theme_skema' ),
					'layout'            => 'row',
					'button_label'      => __( 'Añadir slide móvil', 'theme_skema' ),
					'sub_fields'        => array(
						array(
							'key'           => 'field_skema_lland_slider_img_movil_cell',
							'label'         => __( 'Imagen', 'theme_skema' ),
							'name'          => 'img',
							'type'          => 'image',
							'return_format' => 'array',
							'preview_size'  => 'medium',
							'required'      => 1,
						),
						array(
							'key'           => 'field_skema_lland_slider_img_movil_slide_tagline',
							'label'         => __( 'Línea superior (solo este slide)', 'theme_skema' ),
							'name'          => 'slide_tagline',
							'type'          => 'text',
							'instructions'  => __( 'Opcional. Si se rellena, sustituye la etiqueta global del hero en esta diapositiva.', 'theme_skema' ),
						),
						array(
							'key'           => 'field_skema_lland_slider_img_movil_slide_heading',
							'label'         => __( 'Título (solo este slide)', 'theme_skema' ),
							'name'          => 'slide_heading',
							'type'          => 'text',
							'instructions'  => __( 'Opcional. Si se rellena, sustituye el título global en esta diapositiva.', 'theme_skema' ),
						),
						array(
							'key'           => 'field_skema_lland_slider_img_movil_slide_location',
							'label'         => __( 'Ubicación (solo este slide)', 'theme_skema' ),
							'name'          => 'slide_location',
							'type'          => 'text',
							'instructions'  => __( 'Opcional. Si se rellena, sustituye la ubicación global en esta diapositiva.', 'theme_skema' ),
						),
					),
					'conditional_logic' => array(
						array(
							array(
								'field'    => 'field_skema_lland_hero_tipo',
								'operator' => '==',
								'value'    => 'images',
							),
						),
					),
				),
				array(
					'key'               => 'field_skema_lland_slider_youtube',
					'label'             => __( 'Vídeos YouTube', 'theme_skema' ),
					'name'              => 'skema_lland_slider_youtube',
					'type'              => 'repeater',
					'layout'            => 'row',
					'button_label'      => __( 'Añadir vídeo', 'theme_skema' ),
					'sub_fields'        => array(
						array(
							'key'   => 'field_skema_lland_slider_youtube_url',
							'label' => __( 'URL del vídeo', 'theme_skema' ),
							'name'  => 'youtube_url',
							'type'  => 'url',
						),
						array(
							'key'           => 'field_skema_lland_slider_yt_slide_tagline',
							'label'         => __( 'Línea superior (solo este slide)', 'theme_skema' ),
							'name'          => 'slide_tagline',
							'type'          => 'text',
							'instructions'  => __( 'Opcional. Si se rellena, sustituye la etiqueta global del hero en esta diapositiva.', 'theme_skema' ),
						),
						array(
							'key'           => 'field_skema_lland_slider_yt_slide_heading',
							'label'         => __( 'Título (solo este slide)', 'theme_skema' ),
							'name'          => 'slide_heading',
							'type'          => 'text',
							'instructions'  => __( 'Opcional. Si se rellena, sustituye el título global en esta diapositiva.', 'theme_skema' ),
						),
						array(
							'key'           => 'field_skema_lland_slider_yt_slide_location',
							'label'         => __( 'Ubicación (solo este slide)', 'theme_skema' ),
							'name'          => 'slide_location',
							'type'          => 'text',
							'instructions'  => __( 'Opcional. Si se rellena, sustituye la ubicación global en esta diapositiva.', 'theme_skema' ),
						),
					),
					'conditional_logic' => array(
						array(
							array(
								'field'    => 'field_skema_lland_hero_tipo',
								'operator' => '==',
								'value'    => 'youtube',
							),
						),
					),
				),
				array(
					'key'           => 'field_skema_lland_project_logo',
					'label'         => __( 'Logo del proyecto', 'theme_skema' ),
					'name'          => 'skema_lland_project_logo',
					'type'          => 'image',
					'instructions'  => __( 'Opcional. Dentro del hero (junto al título). Si no hay slider configurado, puede mostrarse solo bajo la cabecera.', 'theme_skema' ),
					'return_format' => 'array',
					'preview_size'  => 'medium',
				),
				array(
					'key'          => 'field_skema_lland_hero_heading',
					'label'        => __( 'Título principal (H1)', 'theme_skema' ),
					'name'         => 'skema_lland_hero_heading',
					'type'         => 'text',
					'instructions' => __( 'Si queda vacío, se usa el título de la entrada. Valor por defecto en cada slide; puedes sobrescribirlo por slide en los repetidores de cabecera.', 'theme_skema' ),
				),
				array(
					'key'          => 'field_skema_lland_hero_tagline',
					'label'        => __( 'Línea superior (etiqueta)', 'theme_skema' ),
					'name'         => 'skema_lland_hero_tagline',
					'type'         => 'text',
					'instructions' => __( 'Ej.: Prelanzamiento 2026 · Proyecto VIS. Texto por defecto en cada slide; puedes sobrescribirlo por slide en los repetidores de cabecera.', 'theme_skema' ),
				),
				array(
					'key'          => 'field_skema_lland_hero_location',
					'label'        => __( 'Ubicación (línea corta)', 'theme_skema' ),
					'name'         => 'skema_lland_hero_location',
					'type'         => 'text',
					'instructions' => __( 'Ej.: Valle del Cauca · Pacífico. Texto por defecto en cada slide; puedes sobrescribirlo por slide en los repetidores de cabecera.', 'theme_skema' ),
				),
				array(
					'key'             => 'field_skema_lland_project_meta_heading',
					'label'           => __( 'Ficha resumen bajo el hero', 'theme_skema' ),
					'name'            => '',
					'type'            => 'message',
					'message'         => __( 'Bloque tipo Renvia (tipología, escala, precio…). Solo se muestra en entradas con fase «Landing completa», encima del contenido del editor. El texto introductorio bajo esta ficha se edita en la pestaña «Prelanding» (campo compartido).', 'theme_skema' ),
					'new_lines'       => 'wpautop',
					'esc_html'        => 0,
				),
				array(
					'key'           => 'field_skema_lland_project_meta_enabled',
					'label'         => __( 'Mostrar ficha resumen', 'theme_skema' ),
					'name'          => 'skema_lland_project_meta_enabled',
					'type'          => 'true_false',
					'instructions'  => __( 'Desactiva para ocultar el bloque sin borrar los datos.', 'theme_skema' ),
					'ui'            => 1,
					'default_value' => 1,
				),
				array(
					'key'          => 'field_skema_lland_project_meta_items',
					'label'        => __( 'Ítems de la ficha (etiqueta + valor)', 'theme_skema' ),
					'name'         => 'skema_lland_project_meta_items',
					'type'         => 'repeater',
					'layout'       => 'row',
					'button_label' => __( 'Añadir ítem', 'theme_skema' ),
					'sub_fields'   => array(
						array(
							'key'           => 'field_skema_lland_project_meta_icon',
							'label'         => __( 'Icono (opcional)', 'theme_skema' ),
							'name'          => 'icon',
							'type'          => 'image',
							'return_format' => 'array',
							'preview_size'  => 'thumbnail',
							'instructions'  => __( 'Si lo dejas vacío se usa un icono por defecto del tema.', 'theme_skema' ),
						),
						array(
							'key'   => 'field_skema_lland_project_meta_label',
							'label' => __( 'Etiqueta', 'theme_skema' ),
							'name'  => 'label',
							'type'  => 'text',
							'required' => 1,
							'placeholder' => __( 'Ej.: Tipología', 'theme_skema' ),
						),
						array(
							'key'   => 'field_skema_lland_project_meta_value',
							'label' => __( 'Valor', 'theme_skema' ),
							'name'  => 'value',
							'type'  => 'text',
							'required' => 1,
							'placeholder' => __( 'Ej.: Apartamento VIS', 'theme_skema' ),
						),
					),
				),
				array(
					'key'             => 'field_skema_lland_content_box_heading',
					'label'           => __( 'Caja de detalle (columna principal)', 'theme_skema' ),
					'name'            => '',
					'type'            => 'message',
					'message'         => __( 'Bloques bajo el contenido del editor. Cada sección solo se muestra si tiene datos en los campos siguientes.', 'theme_skema' ),
					'new_lines'       => 'wpautop',
					'esc_html'        => 0,
				),
				array(
					'key'           => 'field_skema_lland_titulo_desc_proyecto',
					'label'         => __( 'Descripción del proyecto — título de la sección (opcional)', 'theme_skema' ),
					'name'          => 'skema_lland_titulo_desc_proyecto',
					'type'          => 'text',
					'instructions'  => __( 'Si lo dejas vacío se usa «Descripción del proyecto».', 'theme_skema' ),
					'placeholder'   => __( 'Descripción del proyecto', 'theme_skema' ),
				),
				array(
					'key'          => 'field_skema_lland_desc_proyecto',
					'label'        => __( 'Descripción del proyecto', 'theme_skema' ),
					'name'         => 'skema_lland_desc_proyecto',
					'type'         => 'wysiwyg',
					'instructions' => __( 'Si queda vacío, no se muestra el bloque. El encabezado se puede personalizar en el campo anterior.', 'theme_skema' ),
					'tabs'         => 'visual',
					'toolbar'      => 'basic',
					'media_upload' => 0,
					'delay'        => 0,
				),
				array(
					'key'           => 'field_skema_lland_titulo_desc_inmueble',
					'label'         => __( 'Descripción del inmueble (tipología) — título de la sección (opcional)', 'theme_skema' ),
					'name'          => 'skema_lland_titulo_desc_inmueble',
					'type'          => 'text',
					'instructions'  => __( 'Si lo dejas vacío se usa «Descripción del inmueble (tipología)».', 'theme_skema' ),
					'placeholder'   => __( 'Descripción del inmueble (tipología)', 'theme_skema' ),
				),
				array(
					'key'          => 'field_skema_lland_desc_inmueble',
					'label'        => __( 'Descripción del inmueble (tipología)', 'theme_skema' ),
					'name'         => 'skema_lland_desc_inmueble',
					'type'         => 'wysiwyg',
					'instructions' => __( 'Si queda vacío, no se muestra el bloque. El encabezado se puede personalizar en el campo anterior.', 'theme_skema' ),
					'tabs'         => 'visual',
					'toolbar'      => 'basic',
					'media_upload' => 0,
					'delay'        => 0,
				),
				array(
					'key'           => 'field_skema_lland_titulo_zonas_sociales',
					'label'         => __( 'Zonas sociales — título de la sección (opcional)', 'theme_skema' ),
					'name'          => 'skema_lland_titulo_zonas_sociales',
					'type'          => 'text',
					'instructions'  => __( 'Si lo dejas vacío se usa «Zonas sociales».', 'theme_skema' ),
					'placeholder'   => __( 'Zonas sociales', 'theme_skema' ),
				),
				array(
					'key'          => 'field_skema_lland_zonas_intro',
					'label'        => __( 'Zonas sociales — texto', 'theme_skema' ),
					'name'         => 'skema_lland_zonas_intro',
					'type'         => 'wysiwyg',
					'instructions' => __( 'Párrafo(s) antes de la lista. Opcional si solo usas la lista.', 'theme_skema' ),
					'tabs'         => 'visual',
					'toolbar'      => 'basic',
					'media_upload' => 0,
					'delay'        => 0,
				),
				array(
					'key'          => 'field_skema_lland_zonas_items',
					'label'        => __( 'Zonas sociales — lista', 'theme_skema' ),
					'name'         => 'skema_lland_zonas_items',
					'type'         => 'repeater',
					'layout'       => 'row',
					'button_label' => __( 'Añadir ítem', 'theme_skema' ),
					'instructions' => __( 'Cada fila es un elemento de lista. Opcional: icono Font Awesome 6 (mismas clases que en «Ficha del apartamento»). Si no hay filas ni texto arriba, no se muestra la sección.', 'theme_skema' ),
					'sub_fields'   => array(
						array(
							'key'           => 'field_skema_lland_zonas_item_fa',
							'label'         => __( 'Clases Font Awesome', 'theme_skema' ),
							'name'          => 'fa_classes',
							'type'          => 'text',
							'instructions'  => __( 'Opcional. Ej.: fa-solid fa-dumbbell — sin comillas. Si queda vacío solo se muestra el texto.', 'theme_skema' ),
							'placeholder'   => 'fa-solid fa-water-ladder',
						),
						array(
							'key'   => 'field_skema_lland_zonas_item_texto',
							'label' => __( 'Texto', 'theme_skema' ),
							'name'  => 'texto',
							'type'  => 'text',
						),
					),
				),
				array(
					'key'           => 'field_skema_lland_titulo_ficha_apartamento',
					'label'         => __( 'Ficha del apartamento — título de la sección (opcional)', 'theme_skema' ),
					'name'          => 'skema_lland_titulo_ficha_apartamento',
					'type'          => 'text',
					'instructions'  => __( 'Si lo dejas vacío se usa «Ficha del apartamento».', 'theme_skema' ),
					'placeholder'   => __( 'Ficha del apartamento', 'theme_skema' ),
				),
				array(
					'key'             => 'field_skema_lland_ficha_apto_msg',
					'label'           => __( 'Ficha del apartamento (bloque inferior)', 'theme_skema' ),
					'name'            => '',
					'type'            => 'message',
					'message'         => __( 'Sección «Ficha del apartamento» bajo «Zonas sociales». Cada categoría agrupa ítems con icono Font Awesome 6 (clases en texto) y una línea de texto.', 'theme_skema' ),
					'new_lines'       => 'wpautop',
					'esc_html'        => 0,
				),
				array(
					'key'          => 'field_skema_lland_ficha_apto_categorias',
					'label'        => __( 'Ficha del apartamento — categorías e ítems', 'theme_skema' ),
					'name'         => 'skema_lland_ficha_apto_categorias',
					'type'         => 'repeater',
					'layout'       => 'block',
					'button_label' => __( 'Añadir categoría', 'theme_skema' ),
					'instructions' => __( 'Si no hay categorías con ítems rellenados, no se muestra el bloque en la web.', 'theme_skema' ),
					'sub_fields'   => array(
						array(
							'key'           => 'field_skema_lland_ficha_apto_cat_titulo',
							'label'         => __( 'Título de la categoría', 'theme_skema' ),
							'name'          => 'titulo',
							'type'          => 'text',
							'required'      => 1,
							'placeholder'   => __( 'Ej.: Distribución', 'theme_skema' ),
						),
						array(
							'key'          => 'field_skema_lland_ficha_apto_cat_items',
							'label'        => __( 'Ítems', 'theme_skema' ),
							'name'         => 'items',
							'type'         => 'repeater',
							'layout'       => 'row',
							'button_label' => __( 'Añadir ítem', 'theme_skema' ),
							'sub_fields'   => array(
								array(
									'key'           => 'field_skema_lland_ficha_apto_item_fa',
									'label'         => __( 'Clases Font Awesome', 'theme_skema' ),
									'name'          => 'fa_classes',
									'type'          => 'text',
									'instructions'  => __( 'Opcional. Ej.: fa-solid fa-bed — sin comillas. Si queda vacío solo se muestra el texto.', 'theme_skema' ),
									'placeholder'   => 'fa-solid fa-ruler-combined',
								),
								array(
									'key'         => 'field_skema_lland_ficha_apto_item_texto',
									'label'       => __( 'Texto del ítem', 'theme_skema' ),
									'name'        => 'texto',
									'type'        => 'text',
									'required'    => 1,
									'placeholder' => __( 'Ej.: 3 alcobas', 'theme_skema' ),
								),
							),
						),
					),
				),
				array(
					'key'           => 'field_skema_lland_titulo_info_proyecto',
					'label'         => __( 'Información del proyecto — título de la sección (opcional)', 'theme_skema' ),
					'name'          => 'skema_lland_titulo_info_proyecto',
					'type'          => 'text',
					'instructions'  => __( 'Si lo dejas vacío se usa «Información del proyecto».', 'theme_skema' ),
					'placeholder'   => __( 'Información del proyecto', 'theme_skema' ),
				),
				array(
					'key'             => 'field_skema_lland_info_proyecto_msg',
					'label'           => __( 'Información del proyecto', 'theme_skema' ),
					'name'            => '',
					'type'            => 'message',
					'message'         => __( 'Lista tipo Renvia (etiqueta + valor). Si no hay filas, no se muestra el bloque «Información del proyecto».', 'theme_skema' ),
					'new_lines'       => 'wpautop',
					'esc_html'        => 0,
				),
				array(
					'key'          => 'field_skema_lland_info_proyecto_items',
					'label'        => __( 'Información del proyecto — filas', 'theme_skema' ),
					'name'         => 'skema_lland_info_proyecto_items',
					'type'         => 'repeater',
					'layout'       => 'row',
					'button_label' => __( 'Añadir fila', 'theme_skema' ),
					'instructions' => __( 'Ej.: «Nombre» + «Tamborá…». El valor admite enlaces HTML (etiqueta a). No hace falta poner dos puntos al final de la etiqueta.', 'theme_skema' ),
					'sub_fields'   => array(
						array(
							'key'         => 'field_skema_lland_info_item_etiqueta',
							'label'       => __( 'Etiqueta', 'theme_skema' ),
							'name'        => 'etiqueta',
							'type'        => 'text',
							'required'    => 1,
							'placeholder' => __( 'Ej.: Nombre', 'theme_skema' ),
						),
						array(
							'key'          => 'field_skema_lland_info_item_valor',
							'label'        => __( 'Valor', 'theme_skema' ),
							'name'         => 'valor',
							'type'         => 'textarea',
							'rows'         => 2,
							'required'    => 1,
							'placeholder'  => __( 'Texto o HTML simple (enlaces).', 'theme_skema' ),
						),
					),
				),
				array(
					'key'           => 'field_skema_lland_titulo_respaldo',
					'label'         => __( 'Con el respaldo de — título de la sección (opcional)', 'theme_skema' ),
					'name'          => 'skema_lland_titulo_respaldo',
					'type'          => 'text',
					'instructions'  => __( 'Si lo dejas vacío se usa «Con el respaldo de:». Solo se muestra si hay logos en el carrusel.', 'theme_skema' ),
					'placeholder'   => __( 'Con el respaldo de:', 'theme_skema' ),
				),
				array(
					'key'             => 'field_skema_lland_respaldo_msg',
					'label'           => __( 'Con el respaldo de', 'theme_skema' ),
					'name'            => '',
					'type'            => 'message',
					'message'         => __( 'Carrusel de logos y, opcionalmente, botón para descargar un PDF (brochure). La sección se muestra si hay al menos un logo en el carrusel o si configuras un brochure.', 'theme_skema' ),
					'new_lines'       => 'wpautop',
					'esc_html'        => 0,
				),
				array(
					'key'          => 'field_skema_lland_respaldo_slider',
					'label'        => __( 'Respaldo — carrusel de logos', 'theme_skema' ),
					'name'         => 'skema_lland_respaldo_slider',
					'type'         => 'repeater',
					'layout'       => 'row',
					'button_label' => __( 'Añadir empresa', 'theme_skema' ),
					'instructions' => __( 'Logo en PNG/SVG recomendado. El texto encima del logo es opcional.', 'theme_skema' ),
					'sub_fields'   => array(
						array(
							'key'           => 'field_skema_lland_respaldo_texto',
							'label'         => __( 'Texto encima del logo (opcional)', 'theme_skema' ),
							'name'          => 'texto',
							'type'          => 'text',
							'required'      => 0,
							'placeholder'   => __( 'Ej.: Financiamiento VIS', 'theme_skema' ),
							'instructions'  => __( 'Si lo dejas vacío solo se muestra el logo.', 'theme_skema' ),
						),
						array(
							'key'           => 'field_skema_lland_respaldo_logo',
							'label'         => __( 'Logo', 'theme_skema' ),
							'name'          => 'logo',
							'type'          => 'image',
							'return_format' => 'array',
							'preview_size'  => 'medium',
							'required'      => 1,
						),
					),
				),
				array(
					'key'             => 'field_skema_lland_brochure_msg',
					'label'           => __( 'Brochure (PDF)', 'theme_skema' ),
					'name'            => '',
					'type'            => 'message',
					'message'         => __( 'Botón centrado bajo el carrusel (estilo Renvia «theme-btn»). Solo se muestra si subes un PDF válido.', 'theme_skema' ),
					'new_lines'       => 'wpautop',
					'esc_html'        => 0,
				),
				array(
					'key'           => 'field_skema_lland_brochure_archivo',
					'label'         => __( 'Archivo PDF del brochure', 'theme_skema' ),
					'name'          => 'skema_lland_brochure_archivo',
					'type'          => 'file',
					'return_format' => 'array',
					'library'       => 'all',
					'mime_types'    => 'pdf',
					'instructions'  => __( 'Elige un PDF desde Medios. Si queda vacío, no se muestra el botón.', 'theme_skema' ),
				),
				array(
					'key'           => 'field_skema_lland_brochure_etiqueta',
					'label'         => __( 'Texto del botón (opcional)', 'theme_skema' ),
					'name'          => 'skema_lland_brochure_etiqueta',
					'type'          => 'text',
					'placeholder'   => __( 'Descargar brochure', 'theme_skema' ),
					'instructions'  => __( 'Si lo dejas vacío se usa «Descargar brochure».', 'theme_skema' ),
				),
				array(
					'key'           => 'field_skema_lland_brochure_nombre_descarga',
					'label'         => __( 'Nombre del archivo al descargar (opcional)', 'theme_skema' ),
					'name'          => 'skema_lland_brochure_nombre_descarga',
					'type'          => 'text',
					'placeholder'   => 'mi-proyecto-brochure.pdf',
					'instructions'  => __( 'Atributo download del enlace. Si no termina en .pdf se añade automáticamente. Si queda vacío se usa el nombre del archivo en la biblioteca.', 'theme_skema' ),
				),
				array(
					'key'             => 'field_skema_lland_mapa_msg',
					'label'           => __( 'Mapa (Google Maps)', 'theme_skema' ),
					'name'            => '',
					'type'            => 'message',
					'message'         => __( 'Se muestra al final del contenido, después del bloque de respaldo. En Google Maps: Compartir → Insertar un mapa → copia el código HTML o solo la URL que empiece por <code>https://www.google.com/maps/embed</code>.', 'theme_skema' ),
					'new_lines'       => 'wpautop',
					'esc_html'        => 0,
				),
				array(
					'key'           => 'field_skema_lland_mapa_titulo',
					'label'         => __( 'Ubicación — título de la sección (opcional)', 'theme_skema' ),
					'name'          => 'skema_lland_mapa_titulo',
					'type'          => 'text',
					'placeholder'   => __( 'Ubicación', 'theme_skema' ),
					'instructions'  => __( 'Misma línea que el resto de títulos de bloque: si lo dejas vacío y hay mapa, se usa «Ubicación».', 'theme_skema' ),
				),
				array(
					'key'           => 'field_skema_lland_mapa_embed',
					'label'         => __( 'Mapa — código de inserción o URL de embed', 'theme_skema' ),
					'name'          => 'skema_lland_mapa_embed',
					'type'          => 'textarea',
					'rows'          => 4,
					'instructions'  => __( 'Iframe completo desde «Insertar mapa» o únicamente la URL del atributo src (debe contener /maps/embed).', 'theme_skema' ),
					'placeholder'   => 'https://www.google.com/maps/embed?pb=…',
				),
				array(
					'key'           => 'field_skema_lland_titulo_medios',
					'label'         => __( 'Medios del proyecto — título de la sección (opcional)', 'theme_skema' ),
					'name'          => 'skema_lland_titulo_medios',
					'type'          => 'text',
					'instructions'  => __( 'Si lo dejas vacío se usa «Medios del proyecto».', 'theme_skema' ),
					'placeholder'   => __( 'Medios del proyecto', 'theme_skema' ),
				),
				array(
					'key'             => 'field_skema_lland_medios_msg',
					'label'           => __( 'Medios del proyecto', 'theme_skema' ),
					'name'            => '',
					'type'            => 'message',
					'message'         => __( 'Galerías por pestañas (Bootstrap tabs). «Apto modelo» y «Renders»: rejilla + modal. «Plantas» y «Avance de obra»: slider Slick con vista principal + miniaturas; «Avance de obra» admite imagen, MP4 o YouTube, fecha opcional por slide (histórico: los que tienen fecha se ordenan de más antiguo a más reciente) y leyenda opcional. «Videos»: YouTube o MP4. «Zonas sociales»: rejilla de imágenes estáticas (2 cols. móvil, 6 escritorio) con título bajo cada foto. «Maqueta web»: iframe con URL de recorrido virtual (debe ser https). El bloque se muestra si hay contenido en cualquiera de esas secciones.', 'theme_skema' ),
					'new_lines'       => 'wpautop',
					'esc_html'        => 0,
				),
				array(
					'key'          => 'field_skema_lland_medios_apto',
					'label'        => __( 'Medios — Apto modelo (galería)', 'theme_skema' ),
					'name'         => 'skema_lland_medios_apto',
					'type'         => 'repeater',
					'layout'       => 'row',
					'button_label' => __( 'Añadir imagen', 'theme_skema' ),
					'instructions' => __( 'Rejilla 2×4 (móvil / escritorio) con zoom y modal. Leyenda opcional (accesibilidad y texto bajo la imagen en el modal).', 'theme_skema' ),
					'sub_fields'   => array(
						array(
							'key'           => 'field_skema_lland_medios_apto_img',
							'label'         => __( 'Imagen', 'theme_skema' ),
							'name'          => 'imagen',
							'type'          => 'image',
							'return_format' => 'array',
							'preview_size'  => 'medium',
							'required'      => 1,
						),
						array(
							'key'           => 'field_skema_lland_medios_apto_leyenda',
							'label'         => __( 'Leyenda (opcional)', 'theme_skema' ),
							'name'          => 'leyenda',
							'type'          => 'text',
							'instructions'  => __( 'Si la rellenas, sustituye al texto alternativo del archivo para título accesible y pie en el modal.', 'theme_skema' ),
						),
					),
				),
				array(
					'key'          => 'field_skema_lland_medios_renders',
					'label'        => __( 'Medios — Renders (galería)', 'theme_skema' ),
					'name'         => 'skema_lland_medios_renders',
					'type'         => 'repeater',
					'layout'       => 'row',
					'button_label' => __( 'Añadir imagen', 'theme_skema' ),
					'instructions' => __( 'Misma lógica que Apto modelo: rejilla, overlay y modal. Leyenda opcional.', 'theme_skema' ),
					'sub_fields'   => array(
						array(
							'key'           => 'field_skema_lland_medios_renders_img',
							'label'         => __( 'Imagen', 'theme_skema' ),
							'name'          => 'imagen',
							'type'          => 'image',
							'return_format' => 'array',
							'preview_size'  => 'medium',
							'required'      => 1,
						),
						array(
							'key'           => 'field_skema_lland_medios_renders_leyenda',
							'label'         => __( 'Leyenda (opcional)', 'theme_skema' ),
							'name'          => 'leyenda',
							'type'          => 'text',
							'instructions'  => __( 'Si la rellenas, sustituye al texto alternativo del archivo para título accesible y pie en el modal.', 'theme_skema' ),
						),
					),
				),
				array(
					'key'          => 'field_skema_lland_medios_plantas',
					'label'        => __( 'Medios — Plantas (slider)', 'theme_skema' ),
					'name'         => 'skema_lland_medios_plantas',
					'type'         => 'repeater',
					'layout'       => 'row',
					'button_label' => __( 'Añadir imagen', 'theme_skema' ),
					'instructions' => __( 'Slider con imagen grande y carril de miniaturas (como planta Renvia). Leyenda opcional (título accesible de cada slide).', 'theme_skema' ),
					'sub_fields'   => array(
						array(
							'key'           => 'field_skema_lland_medios_plantas_img',
							'label'         => __( 'Imagen', 'theme_skema' ),
							'name'          => 'imagen',
							'type'          => 'image',
							'return_format' => 'array',
							'preview_size'  => 'medium',
							'required'      => 1,
						),
						array(
							'key'           => 'field_skema_lland_medios_plantas_leyenda',
							'label'         => __( 'Leyenda (opcional)', 'theme_skema' ),
							'name'          => 'leyenda',
							'type'          => 'text',
							'instructions'  => __( 'Si la rellenas, sustituye al texto alternativo del archivo para el alt de la vista principal.', 'theme_skema' ),
						),
					),
				),
				array(
					'key'          => 'field_skema_lland_medios_avance',
					'label'        => __( 'Medios — Avance de obra (slider)', 'theme_skema' ),
					'name'         => 'skema_lland_medios_avance',
					'type'         => 'repeater',
					'layout'       => 'row',
					'button_label' => __( 'Añadir slide', 'theme_skema' ),
					'instructions' => __( 'Slider con miniaturas como Plantas. Cada fila puede ser imagen, MP4 o YouTube. La fecha opcional sitúa el slide en el histórico: al mostrar la galería, los slides con fecha se ordenan cronológicamente (los sin fecha quedan al final, en el orden del repetidor).', 'theme_skema' ),
					'sub_fields'   => array(
						array(
							'key'           => 'field_skema_lland_medios_avance_tipo',
							'label'         => __( 'Tipo de slide', 'theme_skema' ),
							'name'          => 'tipo',
							'type'          => 'button_group',
							'choices'       => array(
								'imagen'   => __( 'Imagen', 'theme_skema' ),
								'video'    => __( 'Vídeo MP4', 'theme_skema' ),
								'youtube'  => __( 'YouTube', 'theme_skema' ),
							),
							'default_value' => 'imagen',
							'return_format' => 'value',
						),
						array(
							'key'            => 'field_skema_lland_medios_avance_fecha',
							'label'          => __( 'Fecha del avance (opcional)', 'theme_skema' ),
							'name'           => 'fecha',
							'type'           => 'date_picker',
							'display_format' => 'd/m/Y',
							'return_format'  => 'Y-m-d',
							'first_day'      => 1,
							'instructions'   => __( 'Para situar el slide en el histórico de obra (en pantalla se muestra después de la leyenda, si la rellenas).', 'theme_skema' ),
						),
						array(
							'key'               => 'field_skema_lland_medios_avance_img',
							'label'             => __( 'Imagen', 'theme_skema' ),
							'name'              => 'imagen',
							'type'              => 'image',
							'return_format'     => 'array',
							'preview_size'      => 'medium',
							'required'          => 0,
							'conditional_logic' => array(
								array(
									array(
										'field'    => 'field_skema_lland_medios_avance_tipo',
										'operator' => '==',
										'value'    => 'imagen',
									),
								),
							),
						),
						array(
							'key'               => 'field_skema_lland_medios_avance_video',
							'label'             => __( 'Archivo de vídeo MP4', 'theme_skema' ),
							'name'              => 'video',
							'type'              => 'file',
							'return_format'     => 'array',
							'library'           => 'all',
							'mime_types'        => 'mp4',
							'instructions'      => __( 'Solo MP4 desde Medios.', 'theme_skema' ),
							'conditional_logic' => array(
								array(
									array(
										'field'    => 'field_skema_lland_medios_avance_tipo',
										'operator' => '==',
										'value'    => 'video',
									),
								),
							),
						),
						array(
							'key'               => 'field_skema_lland_medios_avance_poster',
							'label'             => __( 'Portada / miniatura (opcional, solo vídeo)', 'theme_skema' ),
							'name'              => 'poster',
							'type'              => 'image',
							'return_format'     => 'array',
							'preview_size'      => 'medium',
							'instructions'      => __( 'Si no subes portada, en el carril de miniaturas se muestra un icono de reproducción.', 'theme_skema' ),
							'conditional_logic' => array(
								array(
									array(
										'field'    => 'field_skema_lland_medios_avance_tipo',
										'operator' => '==',
										'value'    => 'video',
									),
								),
							),
						),
						array(
							'key'               => 'field_skema_lland_medios_avance_youtube_url',
							'label'             => __( 'URL del vídeo en YouTube', 'theme_skema' ),
							'name'              => 'youtube_url',
							'type'              => 'url',
							'placeholder'       => 'https://www.youtube.com/watch?v=…',
							'instructions'      => __( 'Enlace al vídeo (watch, youtu.be o embed).', 'theme_skema' ),
							'conditional_logic' => array(
								array(
									array(
										'field'    => 'field_skema_lland_medios_avance_tipo',
										'operator' => '==',
										'value'    => 'youtube',
									),
								),
							),
						),
						array(
							'key'          => 'field_skema_lland_medios_avance_leyenda',
							'label'        => __( 'Leyenda / nota del avance (opcional)', 'theme_skema' ),
							'name'         => 'leyenda',
							'type'         => 'text',
							'instructions' => __( 'Texto principal del histórico (p. ej. «Encofrado planta 3»); en pantalla va primero y la fecha detrás si existe. También sirve como texto accesible.', 'theme_skema' ),
						),
					),
				),
				array(
					'key'           => 'field_skema_lland_medios_video_fuente',
					'label'         => __( 'Medios — Video: origen', 'theme_skema' ),
					'name'          => 'skema_lland_medios_video_fuente',
					'type'          => 'button_group',
					'choices'       => array(
						'youtube' => __( 'YouTube', 'theme_skema' ),
						'mp4'     => __( 'MP4 (biblioteca)', 'theme_skema' ),
					),
					'default_value' => 'youtube',
					'return_format' => 'value',
					'instructions'  => __( 'Elige una fuente. Solo se usa la configuración del modo seleccionado.', 'theme_skema' ),
				),
				array(
					'key'               => 'field_skema_lland_medios_video_youtube_url',
					'label'             => __( 'URL del video en YouTube', 'theme_skema' ),
					'name'              => 'skema_lland_medios_video_youtube_url',
					'type'              => 'url',
					'placeholder'       => 'https://www.youtube.com/watch?v=…',
					'instructions'      => __( 'Enlace al video (watch, youtu.be o embed).', 'theme_skema' ),
					'conditional_logic' => array(
						array(
							array(
								'field'    => 'field_skema_lland_medios_video_fuente',
								'operator' => '==',
								'value'    => 'youtube',
							),
						),
					),
				),
				array(
					'key'               => 'field_skema_lland_medios_video_mp4',
					'label'             => __( 'Archivo de video MP4', 'theme_skema' ),
					'name'              => 'skema_lland_medios_video_mp4',
					'type'              => 'file',
					'return_format'     => 'array',
					'library'           => 'all',
					'mime_types'        => 'mp4',
					'instructions'      => __( 'Sube o elige un MP4 desde Medios. Solo se acepta extensión / tipo MP4.', 'theme_skema' ),
					'conditional_logic' => array(
						array(
							array(
								'field'    => 'field_skema_lland_medios_video_fuente',
								'operator' => '==',
								'value'    => 'mp4',
							),
						),
					),
				),
				array(
					'key'               => 'field_skema_lland_medios_video_poster',
					'label'             => __( 'Imagen de portada (opcional, solo MP4)', 'theme_skema' ),
					'name'              => 'skema_lland_medios_video_poster',
					'type'              => 'image',
					'return_format'     => 'array',
					'preview_size'      => 'medium',
					'instructions'      => __( 'Se muestra en el reproductor nativo hasta que el usuario pulse play.', 'theme_skema' ),
					'conditional_logic' => array(
						array(
							array(
								'field'    => 'field_skema_lland_medios_video_fuente',
								'operator' => '==',
								'value'    => 'mp4',
							),
						),
					),
				),
				array(
					'key'          => 'field_skema_lland_medios_video_titulo',
					'label'        => __( 'Título accesible del video (opcional)', 'theme_skema' ),
					'name'         => 'skema_lland_medios_video_titulo',
					'type'         => 'text',
					'instructions' => __( 'Mejora lectores de pantalla (atributo title del iframe o del reproductor). Si queda vacío se usa un texto por defecto.', 'theme_skema' ),
				),
				array(
					'key'          => 'field_skema_lland_medios_zonas',
					'label'        => __( 'Medios — Zonas sociales (galería)', 'theme_skema' ),
					'name'         => 'skema_lland_medios_zonas',
					'type'         => 'repeater',
					'layout'       => 'row',
					'button_label' => __( 'Añadir imagen', 'theme_skema' ),
					'instructions' => __( 'Solo se muestran en la pestaña correspondiente: imagen fija, sin modal. Cada fila puede tener un título corto debajo de la foto.', 'theme_skema' ),
					'sub_fields'   => array(
						array(
							'key'           => 'field_skema_lland_medios_zonas_img',
							'label'         => __( 'Imagen', 'theme_skema' ),
							'name'          => 'imagen',
							'type'          => 'image',
							'return_format' => 'array',
							'preview_size'  => 'medium',
							'required'      => 1,
						),
						array(
							'key'           => 'field_skema_lland_medios_zonas_titulo',
							'label'         => __( 'Título (pie de foto)', 'theme_skema' ),
							'name'          => 'titulo',
							'type'          => 'text',
							'required'      => 1,
							'instructions'  => __( 'Texto breve visible bajo la imagen.', 'theme_skema' ),
						),
					),
				),
				array(
					'key'          => 'field_skema_lland_medios_zonas_nota',
					'label'        => __( 'Medios — Zonas sociales: nota al pie (opcional)', 'theme_skema' ),
					'name'         => 'skema_lland_medios_zonas_nota',
					'type'         => 'textarea',
					'rows'         => 2,
					'instructions' => __( 'Texto pequeño opcional debajo de la rejilla (solo texto, sin HTML).', 'theme_skema' ),
				),
				array(
					'key'           => 'field_skema_lland_medios_maqueta_url',
					'label'         => __( 'Medios — Maqueta web: URL del recorrido virtual', 'theme_skema' ),
					'name'          => 'skema_lland_medios_maqueta_url',
					'type'          => 'url',
					'placeholder'   => 'https://…',
					'instructions'  => __( 'Enlace público que permita embeberse en iframe (Matterport, Kuula, etc.). Solo http/https. Si está vacío, no se muestra la pestaña.', 'theme_skema' ),
				),
				array(
					'key'          => 'field_skema_lland_medios_maqueta_titulo',
					'label'        => __( 'Medios — Maqueta web: título accesible (opcional)', 'theme_skema' ),
					'name'         => 'skema_lland_medios_maqueta_titulo',
					'type'         => 'text',
					'instructions' => __( 'Atributo title del iframe para lectores de pantalla. Si queda vacío se usa un texto por defecto.', 'theme_skema' ),
				),
				array(
					'key'          => 'field_skema_lland_lead_cf7',
					'label'        => __( 'Formulario lateral (Contact Form 7)', 'theme_skema' ),
					'name'         => 'skema_lland_lead_cf7',
					'type'         => 'textarea',
					'rows'         => 2,
					'instructions' => __( 'Shortcode del formulario en la columna «Solicitar información» (debajo del contenido). Si queda vacío, no se muestra esa columna. Solo se aceptan shortcodes que empiecen por [contact-form-7 …].', 'theme_skema' ),
				),
			),
			'location'              => array(
				array(
					array(
						'param'    => 'post_type',
						'operator' => '==',
						'value'    => 'landings',
					),
				),
			),
			'menu_order'            => 1,
			'position'              => 'acf_after_title',
			'style'                 => 'default',
			'label_placement'       => 'top',
			'instruction_placement' => 'label',
			'active'                => true,
		)
	);
}
add_action( 'acf/init', 'theme_skema_acf_register_landing_hero_slider' );
